### ISSUE TITLE
[BUG] Cilium + Multus bridge networking broken

### ISSUE THREAD

**Issue by usrbinkat** [ContainerCraft/Kargo#16]
# Add Multus via [cluster network addons operator](https://github.com/kubevirt/cluster-network-addons-operator)
# Tasks

- [x] add cnao operator
- [x] cnao config
- [x] add br0 resource
- [x] fix cilium strict mode + multus linux bridge bug
- [ ] fix cilium cni missing bridge, macvlan, macvtap, etc cni binaries

## Reference

* example helm values: [ccio/helm/charts/cnao](https://github.com/ContainerCraft/helm/tree/main/charts/cluster-network-addons)

**Comment by usrbinkat** [comment]
cnao is mostly developed and committed to main

need to debug issue w/ multi-home pods, cilium, multus, and kubevirt.

Best lead so far: https://github.com/cilium/cilium/issues/20129#issuecomment-1933615546

**Comment by usrbinkat** [comment]
Resolve issue with multus functionality on Talos using daemonset patching `/run/netns` to `/var/run/netns` to accomodate Talos's read only root filesystem.

**Comment by usrbinkat** [comment]
Next, need to resolve missing CNI binaries when using cilium.
