### ISSUE TITLE
[OPS] EPIC: Migrate to protected `main` branch and implement dev/edge/main enhancement promotion

### ISSUE THREAD

**Issue by usrbinkat** [ContainerCraft/Kargo#26]
# Convert repository to protected 'main' branch

Pre-MVP development is currently proceeding with direct commits to `main` branch. This is poor git hygene and will not scale with project and community growth.

## Recommend

1. [x] activate protected main branch feature
2. [ ] setup dev / edge / main branches as [dev/test/prod] promotion channels
3. [ ] setup release publishing from main > vX.XX.XX semantic versioned branches for pinning deployments to stable releases
4. [ ] document n-1 support & maintenance + accept PRs for minor revision updates to version release branches.

**Comment by usrbinkat** [comment]
protected main. promotion pipelines should be re-located to post-mvp1 into mvp2 as part of the developer tooling next phase of development.
